// 🤖 Generated by Xcode Coding Intelligence powered by Claude Sonnet 4
// 🧑 Reviewed and modified by human

@testable import ChatFeature
import LanguageModelClientTesting
import Testing

@Suite("ChatFeatureUseCase Tests")
struct ChatFeatureUseCaseTests {
    @Test("응답 스트림이 정상적으로 작동하는지 테스트")
    func testStreamResponseSuccess() async throws {
        // Given
        let mockTokens = ["Hello", ", ", "World", "!"]
        let mockClient = MockLanguageModelClient(tokens: mockTokens)
        let useCase = ChatFeatureUseCase(repository: mockClient)
        let prompt = "Say hello"
        
        // When
        var receivedResponses = [String]()
        for try await response in useCase.streamResponse(to: prompt) {
            receivedResponses.append(response)
        }
        
        // Then
        let expectedResponses = mockTokens.toLanguageModelResponses()
        #expect(receivedResponses == expectedResponses, "받은 응답들이 기대하는 응답들과 일치해야 합니다.")
    }
    
    @Test("응답 스트림이 정상적으로 에러를 전파하는지 테스트")
    func testStreamResponseError() async throws {
        // Given
        let mockClient = MockLanguageModelClient(shouldThrowError: true)
        let useCase = ChatFeatureUseCase(repository: mockClient)
        let prompt = "This will fail"
        
        // When & Then
        await #expect(throws: MockLanguageModelError.self) {
            for try await _ in useCase.streamResponse(to: prompt) {}
        }
    }
    
    @Test("빈 응답 스트림 테스트")
    func testStreamResponseWithEmptyResponse() async throws {
        // Given
        let mockClient = MockLanguageModelClient(tokens: [])
        let useCase = ChatFeatureUseCase(repository: mockClient)
        let prompt = "Empty response test"
        
        // When
        var receivedResponses = [String]()
        for try await response in useCase.streamResponse(to: prompt) {
            receivedResponses.append(response)
        }
        
        // Then
        #expect(receivedResponses.isEmpty, "빈 응답 스트림의 경우 받은 응답도 비어있어야 합니다.")
    }
    
    @Test("단일 토큰 응답 스트림 테스트")
    func testStreamResponseWithSingleToken() async throws {
        // Given
        let singleToken = "SingleToken"
        let mockClient = MockLanguageModelClient(tokens: [singleToken])
        let useCase = ChatFeatureUseCase(repository: mockClient)
        let prompt = "Single token test"
        
        // When
        var receivedResponses = [String]()
        for try await response in useCase.streamResponse(to: prompt) {
            receivedResponses.append(response)
        }
        
        // Then
        #expect(receivedResponses == [singleToken], "받은 응답이 기대하는 응답과 일치해야 합니다.")
    }
    
    @Test("많은 토큰 수의 응답 스트림 테스트")
    func testStreamResponseWithLargeNumberOfTokens() async throws {
        // Given
        let largeNumberOfTokens = Array(1...100).map { "Token\($0)" }
        let mockClient = MockLanguageModelClient(
            tokens: largeNumberOfTokens,
            delayBetweenTokens: 0.01
        )
        let useCase = ChatFeatureUseCase(repository: mockClient)
        let prompt = "Large number of tokens test"
        
        // When
        var receivedResponses = [String]()
        for try await response in useCase.streamResponse(to: prompt) {
            receivedResponses.append(response)
        }
        
        // Then
        let expectedResponses = largeNumberOfTokens.toLanguageModelResponses()
        #expect(receivedResponses == expectedResponses, "받은 응답들이 기대하는 응답들과 일치해야 합니다.")
    }
}
